# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pa/workspace/kakuro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pa/workspace/kakuro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pa/workspace/kakuro/CMakeFiles /home/pa/workspace/kakuro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pa/workspace/kakuro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kakuro

# Build rule for target.
kakuro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kakuro
.PHONY : kakuro

# fast build rule for target.
kakuro/fast:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/build
.PHONY : kakuro/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/main.cpp.s
.PHONY : main.cpp.s

src/Case.o: src/Case.cpp.o

.PHONY : src/Case.o

# target to build an object file
src/Case.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/Case.cpp.o
.PHONY : src/Case.cpp.o

src/Case.i: src/Case.cpp.i

.PHONY : src/Case.i

# target to preprocess a source file
src/Case.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/Case.cpp.i
.PHONY : src/Case.cpp.i

src/Case.s: src/Case.cpp.s

.PHONY : src/Case.s

# target to generate assembly for a file
src/Case.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/Case.cpp.s
.PHONY : src/Case.cpp.s

src/csp/algo/algorithm_backtrack.o: src/csp/algo/algorithm_backtrack.cpp.o

.PHONY : src/csp/algo/algorithm_backtrack.o

# target to build an object file
src/csp/algo/algorithm_backtrack.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_backtrack.cpp.o
.PHONY : src/csp/algo/algorithm_backtrack.cpp.o

src/csp/algo/algorithm_backtrack.i: src/csp/algo/algorithm_backtrack.cpp.i

.PHONY : src/csp/algo/algorithm_backtrack.i

# target to preprocess a source file
src/csp/algo/algorithm_backtrack.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_backtrack.cpp.i
.PHONY : src/csp/algo/algorithm_backtrack.cpp.i

src/csp/algo/algorithm_backtrack.s: src/csp/algo/algorithm_backtrack.cpp.s

.PHONY : src/csp/algo/algorithm_backtrack.s

# target to generate assembly for a file
src/csp/algo/algorithm_backtrack.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_backtrack.cpp.s
.PHONY : src/csp/algo/algorithm_backtrack.cpp.s

src/csp/algo/algorithm_forward_checking.o: src/csp/algo/algorithm_forward_checking.cpp.o

.PHONY : src/csp/algo/algorithm_forward_checking.o

# target to build an object file
src/csp/algo/algorithm_forward_checking.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_forward_checking.cpp.o
.PHONY : src/csp/algo/algorithm_forward_checking.cpp.o

src/csp/algo/algorithm_forward_checking.i: src/csp/algo/algorithm_forward_checking.cpp.i

.PHONY : src/csp/algo/algorithm_forward_checking.i

# target to preprocess a source file
src/csp/algo/algorithm_forward_checking.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_forward_checking.cpp.i
.PHONY : src/csp/algo/algorithm_forward_checking.cpp.i

src/csp/algo/algorithm_forward_checking.s: src/csp/algo/algorithm_forward_checking.cpp.s

.PHONY : src/csp/algo/algorithm_forward_checking.s

# target to generate assembly for a file
src/csp/algo/algorithm_forward_checking.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/algorithm_forward_checking.cpp.s
.PHONY : src/csp/algo/algorithm_forward_checking.cpp.s

src/csp/algo/record.o: src/csp/algo/record.cpp.o

.PHONY : src/csp/algo/record.o

# target to build an object file
src/csp/algo/record.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/record.cpp.o
.PHONY : src/csp/algo/record.cpp.o

src/csp/algo/record.i: src/csp/algo/record.cpp.i

.PHONY : src/csp/algo/record.i

# target to preprocess a source file
src/csp/algo/record.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/record.cpp.i
.PHONY : src/csp/algo/record.cpp.i

src/csp/algo/record.s: src/csp/algo/record.cpp.s

.PHONY : src/csp/algo/record.s

# target to generate assembly for a file
src/csp/algo/record.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algo/record.cpp.s
.PHONY : src/csp/algo/record.cpp.s

src/csp/algorithm.o: src/csp/algorithm.cpp.o

.PHONY : src/csp/algorithm.o

# target to build an object file
src/csp/algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algorithm.cpp.o
.PHONY : src/csp/algorithm.cpp.o

src/csp/algorithm.i: src/csp/algorithm.cpp.i

.PHONY : src/csp/algorithm.i

# target to preprocess a source file
src/csp/algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algorithm.cpp.i
.PHONY : src/csp/algorithm.cpp.i

src/csp/algorithm.s: src/csp/algorithm.cpp.s

.PHONY : src/csp/algorithm.s

# target to generate assembly for a file
src/csp/algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/algorithm.cpp.s
.PHONY : src/csp/algorithm.cpp.s

src/csp/compare_variables.o: src/csp/compare_variables.cpp.o

.PHONY : src/csp/compare_variables.o

# target to build an object file
src/csp/compare_variables.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/compare_variables.cpp.o
.PHONY : src/csp/compare_variables.cpp.o

src/csp/compare_variables.i: src/csp/compare_variables.cpp.i

.PHONY : src/csp/compare_variables.i

# target to preprocess a source file
src/csp/compare_variables.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/compare_variables.cpp.i
.PHONY : src/csp/compare_variables.cpp.i

src/csp/compare_variables.s: src/csp/compare_variables.cpp.s

.PHONY : src/csp/compare_variables.s

# target to generate assembly for a file
src/csp/compare_variables.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/compare_variables.cpp.s
.PHONY : src/csp/compare_variables.cpp.s

src/csp/constraint/csp_constraint_difference.o: src/csp/constraint/csp_constraint_difference.cpp.o

.PHONY : src/csp/constraint/csp_constraint_difference.o

# target to build an object file
src/csp/constraint/csp_constraint_difference.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_difference.cpp.o
.PHONY : src/csp/constraint/csp_constraint_difference.cpp.o

src/csp/constraint/csp_constraint_difference.i: src/csp/constraint/csp_constraint_difference.cpp.i

.PHONY : src/csp/constraint/csp_constraint_difference.i

# target to preprocess a source file
src/csp/constraint/csp_constraint_difference.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_difference.cpp.i
.PHONY : src/csp/constraint/csp_constraint_difference.cpp.i

src/csp/constraint/csp_constraint_difference.s: src/csp/constraint/csp_constraint_difference.cpp.s

.PHONY : src/csp/constraint/csp_constraint_difference.s

# target to generate assembly for a file
src/csp/constraint/csp_constraint_difference.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_difference.cpp.s
.PHONY : src/csp/constraint/csp_constraint_difference.cpp.s

src/csp/constraint/csp_constraint_solution.o: src/csp/constraint/csp_constraint_solution.cpp.o

.PHONY : src/csp/constraint/csp_constraint_solution.o

# target to build an object file
src/csp/constraint/csp_constraint_solution.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_solution.cpp.o
.PHONY : src/csp/constraint/csp_constraint_solution.cpp.o

src/csp/constraint/csp_constraint_solution.i: src/csp/constraint/csp_constraint_solution.cpp.i

.PHONY : src/csp/constraint/csp_constraint_solution.i

# target to preprocess a source file
src/csp/constraint/csp_constraint_solution.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_solution.cpp.i
.PHONY : src/csp/constraint/csp_constraint_solution.cpp.i

src/csp/constraint/csp_constraint_solution.s: src/csp/constraint/csp_constraint_solution.cpp.s

.PHONY : src/csp/constraint/csp_constraint_solution.s

# target to generate assembly for a file
src/csp/constraint/csp_constraint_solution.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_solution.cpp.s
.PHONY : src/csp/constraint/csp_constraint_solution.cpp.s

src/csp/constraint/csp_constraint_sum.o: src/csp/constraint/csp_constraint_sum.cpp.o

.PHONY : src/csp/constraint/csp_constraint_sum.o

# target to build an object file
src/csp/constraint/csp_constraint_sum.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_sum.cpp.o
.PHONY : src/csp/constraint/csp_constraint_sum.cpp.o

src/csp/constraint/csp_constraint_sum.i: src/csp/constraint/csp_constraint_sum.cpp.i

.PHONY : src/csp/constraint/csp_constraint_sum.i

# target to preprocess a source file
src/csp/constraint/csp_constraint_sum.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_sum.cpp.i
.PHONY : src/csp/constraint/csp_constraint_sum.cpp.i

src/csp/constraint/csp_constraint_sum.s: src/csp/constraint/csp_constraint_sum.cpp.s

.PHONY : src/csp/constraint/csp_constraint_sum.s

# target to generate assembly for a file
src/csp/constraint/csp_constraint_sum.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/constraint/csp_constraint_sum.cpp.s
.PHONY : src/csp/constraint/csp_constraint_sum.cpp.s

src/csp/csp_constraint.o: src/csp/csp_constraint.cpp.o

.PHONY : src/csp/csp_constraint.o

# target to build an object file
src/csp/csp_constraint.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_constraint.cpp.o
.PHONY : src/csp/csp_constraint.cpp.o

src/csp/csp_constraint.i: src/csp/csp_constraint.cpp.i

.PHONY : src/csp/csp_constraint.i

# target to preprocess a source file
src/csp/csp_constraint.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_constraint.cpp.i
.PHONY : src/csp/csp_constraint.cpp.i

src/csp/csp_constraint.s: src/csp/csp_constraint.cpp.s

.PHONY : src/csp/csp_constraint.s

# target to generate assembly for a file
src/csp/csp_constraint.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_constraint.cpp.s
.PHONY : src/csp/csp_constraint.cpp.s

src/csp/csp_variable.o: src/csp/csp_variable.cpp.o

.PHONY : src/csp/csp_variable.o

# target to build an object file
src/csp/csp_variable.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_variable.cpp.o
.PHONY : src/csp/csp_variable.cpp.o

src/csp/csp_variable.i: src/csp/csp_variable.cpp.i

.PHONY : src/csp/csp_variable.i

# target to preprocess a source file
src/csp/csp_variable.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_variable.cpp.i
.PHONY : src/csp/csp_variable.cpp.i

src/csp/csp_variable.s: src/csp/csp_variable.cpp.s

.PHONY : src/csp/csp_variable.s

# target to generate assembly for a file
src/csp/csp_variable.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/csp_variable.cpp.s
.PHONY : src/csp/csp_variable.cpp.s

src/csp/heuristic.o: src/csp/heuristic.cpp.o

.PHONY : src/csp/heuristic.o

# target to build an object file
src/csp/heuristic.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/heuristic.cpp.o
.PHONY : src/csp/heuristic.cpp.o

src/csp/heuristic.i: src/csp/heuristic.cpp.i

.PHONY : src/csp/heuristic.i

# target to preprocess a source file
src/csp/heuristic.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/heuristic.cpp.i
.PHONY : src/csp/heuristic.cpp.i

src/csp/heuristic.s: src/csp/heuristic.cpp.s

.PHONY : src/csp/heuristic.s

# target to generate assembly for a file
src/csp/heuristic.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/heuristic.cpp.s
.PHONY : src/csp/heuristic.cpp.s

src/csp/history.o: src/csp/history.cpp.o

.PHONY : src/csp/history.o

# target to build an object file
src/csp/history.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/history.cpp.o
.PHONY : src/csp/history.cpp.o

src/csp/history.i: src/csp/history.cpp.i

.PHONY : src/csp/history.i

# target to preprocess a source file
src/csp/history.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/history.cpp.i
.PHONY : src/csp/history.cpp.i

src/csp/history.s: src/csp/history.cpp.s

.PHONY : src/csp/history.s

# target to generate assembly for a file
src/csp/history.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/history.cpp.s
.PHONY : src/csp/history.cpp.s

src/csp/solution.o: src/csp/solution.cpp.o

.PHONY : src/csp/solution.o

# target to build an object file
src/csp/solution.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/solution.cpp.o
.PHONY : src/csp/solution.cpp.o

src/csp/solution.i: src/csp/solution.cpp.i

.PHONY : src/csp/solution.i

# target to preprocess a source file
src/csp/solution.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/solution.cpp.i
.PHONY : src/csp/solution.cpp.i

src/csp/solution.s: src/csp/solution.cpp.s

.PHONY : src/csp/solution.s

# target to generate assembly for a file
src/csp/solution.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/csp/solution.cpp.s
.PHONY : src/csp/solution.cpp.s

src/forward.o: src/forward.cpp.o

.PHONY : src/forward.o

# target to build an object file
src/forward.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/forward.cpp.o
.PHONY : src/forward.cpp.o

src/forward.i: src/forward.cpp.i

.PHONY : src/forward.i

# target to preprocess a source file
src/forward.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/forward.cpp.i
.PHONY : src/forward.cpp.i

src/forward.s: src/forward.cpp.s

.PHONY : src/forward.s

# target to generate assembly for a file
src/forward.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/forward.cpp.s
.PHONY : src/forward.cpp.s

src/kakuro_parser.o: src/kakuro_parser.cpp.o

.PHONY : src/kakuro_parser.o

# target to build an object file
src/kakuro_parser.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/kakuro_parser.cpp.o
.PHONY : src/kakuro_parser.cpp.o

src/kakuro_parser.i: src/kakuro_parser.cpp.i

.PHONY : src/kakuro_parser.i

# target to preprocess a source file
src/kakuro_parser.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/kakuro_parser.cpp.i
.PHONY : src/kakuro_parser.cpp.i

src/kakuro_parser.s: src/kakuro_parser.cpp.s

.PHONY : src/kakuro_parser.s

# target to generate assembly for a file
src/kakuro_parser.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/kakuro_parser.cpp.s
.PHONY : src/kakuro_parser.cpp.s

src/ostream.o: src/ostream.cpp.o

.PHONY : src/ostream.o

# target to build an object file
src/ostream.cpp.o:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/ostream.cpp.o
.PHONY : src/ostream.cpp.o

src/ostream.i: src/ostream.cpp.i

.PHONY : src/ostream.i

# target to preprocess a source file
src/ostream.cpp.i:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/ostream.cpp.i
.PHONY : src/ostream.cpp.i

src/ostream.s: src/ostream.cpp.s

.PHONY : src/ostream.s

# target to generate assembly for a file
src/ostream.cpp.s:
	$(MAKE) -f CMakeFiles/kakuro.dir/build.make CMakeFiles/kakuro.dir/src/ostream.cpp.s
.PHONY : src/ostream.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kakuro"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Case.o"
	@echo "... src/Case.i"
	@echo "... src/Case.s"
	@echo "... src/csp/algo/algorithm_backtrack.o"
	@echo "... src/csp/algo/algorithm_backtrack.i"
	@echo "... src/csp/algo/algorithm_backtrack.s"
	@echo "... src/csp/algo/algorithm_forward_checking.o"
	@echo "... src/csp/algo/algorithm_forward_checking.i"
	@echo "... src/csp/algo/algorithm_forward_checking.s"
	@echo "... src/csp/algo/record.o"
	@echo "... src/csp/algo/record.i"
	@echo "... src/csp/algo/record.s"
	@echo "... src/csp/algorithm.o"
	@echo "... src/csp/algorithm.i"
	@echo "... src/csp/algorithm.s"
	@echo "... src/csp/compare_variables.o"
	@echo "... src/csp/compare_variables.i"
	@echo "... src/csp/compare_variables.s"
	@echo "... src/csp/constraint/csp_constraint_difference.o"
	@echo "... src/csp/constraint/csp_constraint_difference.i"
	@echo "... src/csp/constraint/csp_constraint_difference.s"
	@echo "... src/csp/constraint/csp_constraint_solution.o"
	@echo "... src/csp/constraint/csp_constraint_solution.i"
	@echo "... src/csp/constraint/csp_constraint_solution.s"
	@echo "... src/csp/constraint/csp_constraint_sum.o"
	@echo "... src/csp/constraint/csp_constraint_sum.i"
	@echo "... src/csp/constraint/csp_constraint_sum.s"
	@echo "... src/csp/csp_constraint.o"
	@echo "... src/csp/csp_constraint.i"
	@echo "... src/csp/csp_constraint.s"
	@echo "... src/csp/csp_variable.o"
	@echo "... src/csp/csp_variable.i"
	@echo "... src/csp/csp_variable.s"
	@echo "... src/csp/heuristic.o"
	@echo "... src/csp/heuristic.i"
	@echo "... src/csp/heuristic.s"
	@echo "... src/csp/history.o"
	@echo "... src/csp/history.i"
	@echo "... src/csp/history.s"
	@echo "... src/csp/solution.o"
	@echo "... src/csp/solution.i"
	@echo "... src/csp/solution.s"
	@echo "... src/forward.o"
	@echo "... src/forward.i"
	@echo "... src/forward.s"
	@echo "... src/kakuro_parser.o"
	@echo "... src/kakuro_parser.i"
	@echo "... src/kakuro_parser.s"
	@echo "... src/ostream.o"
	@echo "... src/ostream.i"
	@echo "... src/ostream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

